spring.application.name=fatecads

# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/fatecads_db
spring.datasource.username=postgres
spring.datasource.password=123456

# Automatically update the database schema
spring.jpa.hibernate.ddl-auto=update

# Show SQL queries in the console
spring.jpa.show-sql=true

# Do not format SQL queries
spring.jpa.properties.hibernate.format_sql=false

# Server port configuration
server.port=8080

# Gmail SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=johnzndx@gmail.com
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8
spring.mail.from=johnzndx@gmail.com